name: Auto Label Approved PR

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  label-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Add Approved Label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['gssoc approved']
            })
